defaults:
  - default
  - _self_

# Override from `default` config
id: isaac_sim_environment
action_repeat: 1
max_episode_steps: 2048
sync_env: True
screen_size: 128

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.isaacsim.IsaacSimWrapper
  map_size: [128, 128]
  camera_rgb_size: [128, 128]
  camera_height: 0.6
  camera_linear_velocity: 2.0
  camera_angular_velocity: 3.1415927
  camera_parent: /World
  camera_name: Camera_
  seed: null
