defaults:
  - default
  - _self_

# Override from `default` config
id: isaac_sim_environment
action_repeat: 1
max_episode_steps: 1000
sync_env: True

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.isaacsim.IsaacSimWrapper
  map_size: [128, 128]
  rgb_size: [128, 128]
  seed: null
