# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: isaacsim
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 1
  action_repeat: 1
  max_episode_steps: -1
  wrapper:
    map_size: [84, 84]
    rgb_size: [84, 84]

# Checkpoint
checkpoint:
  every: 1000

# Buffer
buffer:
  size: 500_000
  checkpoint: True
  memmap: True

# Algorithm
algo:
  per_rank_batch_size: 8
  total_steps: 500_000
  cnn_keys:
    encoder:
      - local_map
      - rgb_image
    decoder:
      - local_map
  mlp_keys:
    encoder:
      - position
  learning_starts: 1000
  replay_ratio: 0.5

# Metric
metric:
  log_level: 0
  log_every: 1000

fabric:
  accelerator: cuda
  precision: bf16-mixed
