# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: isaacsim
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 8
  action_repeat: 1
  max_episode_steps: -1
  wrapper:
    map_size: [128, 128]
    camera_rgb_size: [128, 128]

# Checkpoint
checkpoint:
  every: 10000

# Buffer
buffer:
  size: 1_000_000
  checkpoint: True
  memmap: True

# Algorithm
algo:
  per_rank_batch_size: 16
  per_rank_sequence_length: 32
  total_steps: 1_000_000
  cnn_keys:
    encoder:
      - map
      - depth
    decoder:
      - map
  mlp_keys:
    encoder:
      - goal
      - heading
      - orientation
      - distance
  learning_starts: 10000
  replay_ratio: 0.5

# Metric
metric:
  log_level: 1
  log_every: 1000
  aggregator:
    metrics:
      Game/curriculum_level: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Game/goal: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Game/collision: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Game/success_rate: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Game/collision_dynamic: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}
      Game/collision_static: 
        _target_: torchmetrics.MeanMetric
        sync_on_compute: ${metric.sync_on_compute}




fabric:
  accelerator: cuda
  precision: bf16-mixed
